name = "airdrop-send-transactions"
type = "webpack"

account_id = "99b9572de9d3c33774965949416b82c9"
workers_dev = true
route = ""
zone_id = "88e06eefedbbd140a12ac3dd1b21a7af"
compatibility_date = "2022-03-15"

usage_model = "bundled"

kv_namespaces = [ 
    { binding = "reward_tiers_test", id = "d8a783f7388d4c6a8a34db1848326505", preview_id = "d8a783f7388d4c6a8a34db1848326505" },
    { binding = "withdrawal_queue_test", id = "bd03245aabe145c19ab703cea48bd3c7", preview_id = "bd03245aabe145c19ab703cea48bd3c7" }
]

[vars]
CF_RPC_ENDPOINT = "https://rpc.cheqd.net:443"
CF_NUMBER_OF_DISTRIBUTORS = 2
CF_MAX_SAFE_TX_PER_BLOCK = 2

# the following are encrypted
CF_MNEMONICS = "***REMOVED***,***REMOVED******REMOVED***"
# CF_MNEMONICS = "***REMOVED***,***REMOVED******REMOVED***,***REMOVED***,***REMOVED******REMOVED***,***REMOVED******REMOVED***"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
