name = "cosmjs-transactions"
type = "webpack"

account_id = "99b9572de9d3c33774965949416b82c9"
workers_dev = true
route = ""
zone_id = "afe3b66243382f27140e6feeaae848b5"
compatibility_date = "2022-03-15"

kv_namespaces = [ 
    { binding = "community_airdrop", id = "f42e3da0c31744c7b0b0b3879b6dd0cc", preview_id = "f42e3da0c31744c7b0b0b3879b6dd0cc" },
    { binding = "withdrawal_transactions_queue", id = "26da33ddd6fd4a94898dd84094f5a9c6", preview_id = "26da33ddd6fd4a94898dd84094f5a9c6" }
]

[vars]
RPC_ENDPOINT = "https://rpc.cheqd.net:443"

# [secrets]
# DISTRIBUTOR_1_MNEMONIC
# DISTRIBUTOR_2_MNEMONIC

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"