name = "claim-transactions"
type = "javascript"

account_id = "99b9572de9d3c33774965949416b82c9"
workers_dev = true
route = ""
zone_id = "88e06eefedbbd140a12ac3dd1b21a7af"
compatibility_date = "2022-03-15"

kv_namespaces = [ 
    { binding = "reward-tiers-test", id = "1639b8f774be47a08e25b160871cd8fe", preview_id = "1639b8f774be47a08e25b160871cd8fe" },
    { binding = "withdrawal-queue-test", id = "cd1c4cf6dcb14bb0b8d6985a91b8812f", preview_id = "cd1c4cf6dcb14bb0b8d6985a91b8812f" }
]

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
