name = "claim-transactions"
type = "javascript"

account_id = ""
workers_dev = true
zone_id = ""
compatibility_date = "2022-03-15"

kv_namespaces = [ 
    { binding = "reward_tiers", id = "d8a783f7388d4c6a8a34db1848326505", preview_id = "d8a783f7388d4c6a8a34db1848326505" },
    { binding = "withdrawal_queue", id = "bd03245aabe145c19ab703cea48bd3c7", preview_id = "bd03245aabe145c19ab703cea48bd3c7" },
    { binding = "airdrop_denylist", id = "2978b679f1a4460abb99b8fe62c22f3e", preview_id = "2978b679f1a4460abb99b8fe62c22f3e" }
]

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
