name = "claim-transactions"
type = "javascript"

account_id = "99b9572de9d3c33774965949416b82c9"
workers_dev = true
route = ""
zone_id = "88e06eefedbbd140a12ac3dd1b21a7af"
compatibility_date = "2022-03-15"

kv_namespaces = [ 
    { binding = "reward_tiers_test", id = "d8a783f7388d4c6a8a34db1848326505", preview_id = "d8a783f7388d4c6a8a34db1848326505" },
    { binding = "withdrawal_queue_test", id = "bd03245aabe145c19ab703cea48bd3c7", preview_id = "bd03245aabe145c19ab703cea48bd3c7" },
    { binding = "airdrop_denylist", id = "2978b679f1a4460abb99b8fe62c22f3e", preview_id = "2978b679f1a4460abb99b8fe62c22f3e" }
]

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"