name: Cloudflare Deploy

on:
  push:
    branches:
      - main

jobs:
  publish-claim-tx:
    name: Publish Claim Transactions to Cloudflare
    defaults:
      run:
        working-directory: claim-transactions

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@master
      
      - name: Publish Claim Transactions to Cloudflare
        uses: cloudflare/wrangler-action@1.3.0
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          
          postCommand: |
          echo "*** post commands ***"
          wrangler kv
          echo "******"

publish-claim-tx:
  name: Publish Claim Transactions to 
  needs: build-claim-tx
  defaults:
    run:
      working_directory: claim-transactions

  runs_on: ubuntu-latest

  steps:
      - name: Load binary artifact
        uses: actions/download-artifact@v2
        with:
          name: claim-tx
      
      

