name: Cloudflare Deploy

on:
  push:
    branches:
      - main

jobs:
  publish-claim-tx:
    name: Publish Claim Transactions to Cloudflare
    defaults:
      run:
        working-directory: claim-transactions

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@master
      
      - name: Publish Claim Transactions to Cloudflare
        uses: cloudflare/wrangler-action@1.3.0
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
