name: Cloudflare Deploy

on:
  push:
    branches:
      - main

jobs:
  publish-claim-tx:
    name: Publish Claim Transactions to Cloudflare

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Publish Claim Transactions to Cloudflare
        uses: cloudflare/wrangler-action@1.3.0
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: claim-transactions
